# Generated by Django 4.2.1 on 2023-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.CharField(blank=True, max_length=4094, verbose_name="Caption"),
        ),
    ]
