# Generated by Django 4.2.1 on 2023-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="saved",
            field=models.ManyToManyField(
                blank=True, related_name="saved_by", to="app.post"
            ),
        ),
    ]
