# Generated by Django 4.2.1 on 2023-06-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_userprofile_saved"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="favorites",),
    ]
