# Generated by Django 4.2.1 on 2023-06-04 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_userprofile_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saved_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
