# Generated by Django 4.2.1 on 2023-06-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_post_saved_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="saved_time",),
    ]
