# Generated by Django 4.2.1 on 2023-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_userprofile_saved_list"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="following",),
        migrations.AddField(
            model_name="userprofile",
            name="saved_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
