# Generated by Django 4.2.1 on 2023-06-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_userprofile_following"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="saved_list",),
    ]
