# Generated by Django 4.2.1 on 2023-06-05 15:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_userprofile_saved_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pfp",
            field=models.ImageField(
                blank=True,
                default="default_img.jpg",
                null=True,
                upload_to=app.models.user_directory_path_profile,
                verbose_name="Profile Picture",
            ),
        ),
    ]
