# Generated by Django 4.2.1 on 2023-06-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_messagepost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagepost", old_name="reciever", new_name="receiver",
        ),
    ]
