# Generated by Django 4.2.1 on 2023-06-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_notifications"),
    ]

    operations = [
        migrations.RemoveField(model_name="notifications", name="post",),
        migrations.RemoveField(model_name="notifications", name="sender",),
        migrations.RemoveField(model_name="notifications", name="user",),
        migrations.DeleteModel(name="MessagePost",),
        migrations.DeleteModel(name="Notifications",),
    ]
